<?php

return [
    'states' => [
        [
            'name'      => 'Baden-Württemberg',
            'slug'      => 'baden-wuerttemberg',
            'kuerzel'   => 'bw',
            'iso'       => 'DE-BW',
            'short'     => 'BW',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Bayern',
            'slug'      => 'bayern',
            'kuerzel'   => 'by',
            'iso'       => 'DE-BY',
            'short'     => 'BY',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Berlin',
            'slug'      => 'berlin',
            'kuerzel'   => 'be',
            'iso'       => 'DE-BE',
            'short'     => 'BE',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Brandenburg',
            'slug'      => 'brandenburg',
            'kuerzel'   => 'bb',
            'iso'       => 'DE-BB',
            'short'     => 'BB',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Bremen',
            'slug'      => 'bremen',
            'kuerzel'   => 'hb',
            'iso'       => 'DE-HB',
            'short'     => 'HB',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Hamburg',
            'slug'      => 'hamburg',
            'kuerzel'   => 'hh',
            'iso'       => 'DE-HH',
            'short'     => 'HH',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Hessen',
            'slug'      => 'hessen',
            'kuerzel'   => 'he',
            'iso'       => 'DE-HE',
            'short'     => 'HE',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Mecklenburg-Vorpommern',
            'slug'      => 'mecklenburg-vorpommern',
            'kuerzel'   => 'mv',
            'iso'       => 'DE-MV',
            'short'     => 'MV',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Niedersachsen',
            'slug'      => 'niedersachsen',
            'kuerzel'   => 'ni',
            'iso'       => 'DE-NI',
            'short'     => 'NI',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Nordrhein-Westfalen',
            'slug'      => 'nordrhein-westfalen',
            'kuerzel'   => 'nw',
            'iso'       => 'DE-NW',
            'short'     => 'NRW',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Rheinland-Pfalz',
            'slug'      => 'rheinland-pfalz',
            'kuerzel'   => 'rp',
            'iso'       => 'DE-RP',
            'short'     => 'RLP',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Saarland',
            'slug'      => 'saarland',
            'kuerzel'   => 'sl',
            'iso'       => 'DE-SL',
            'short'     => 'SL',
            'in_prefix' => 'im ',
        ],
        [
            'name'      => 'Sachsen',
            'slug'      => 'sachsen',
            'kuerzel'   => 'sn',
            'iso'       => 'DE-SN',
            'short'     => 'SN',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Sachsen-Anhalt',
            'slug'      => 'sachsen-anhalt',
            'kuerzel'   => 'st',
            'iso'       => 'DE-ST',
            'short'     => 'ST',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Schleswig-Holstein',
            'slug'      => 'schleswig-holstein',
            'kuerzel'   => 'sh',
            'iso'       => 'DE-SH',
            'short'     => 'SH',
            'in_prefix' => 'in ',
        ],
        [
            'name'      => 'Thüringen',
            'slug'      => 'thueringen',
            'kuerzel'   => 'th',
            'iso'       => 'DE-TH',
            'short'     => 'TH',
            'in_prefix' => 'in ',
        ],
    ],
];
